require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EstacaosController do

  # This should return the minimal set of attributes required to create a valid
  # Estacao. As you add validations to Estacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstacaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all estacaos as @estacaos" do
      estacao = Estacao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:estacaos).should eq([estacao])
    end
  end

  describe "GET show" do
    it "assigns the requested estacao as @estacao" do
      estacao = Estacao.create! valid_attributes
      get :show, {:id => estacao.to_param}, valid_session
      assigns(:estacao).should eq(estacao)
    end
  end

  describe "GET new" do
    it "assigns a new estacao as @estacao" do
      get :new, {}, valid_session
      assigns(:estacao).should be_a_new(Estacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested estacao as @estacao" do
      estacao = Estacao.create! valid_attributes
      get :edit, {:id => estacao.to_param}, valid_session
      assigns(:estacao).should eq(estacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Estacao" do
        expect {
          post :create, {:estacao => valid_attributes}, valid_session
        }.to change(Estacao, :count).by(1)
      end

      it "assigns a newly created estacao as @estacao" do
        post :create, {:estacao => valid_attributes}, valid_session
        assigns(:estacao).should be_a(Estacao)
        assigns(:estacao).should be_persisted
      end

      it "redirects to the created estacao" do
        post :create, {:estacao => valid_attributes}, valid_session
        response.should redirect_to(Estacao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estacao as @estacao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estacao.any_instance.stub(:save).and_return(false)
        post :create, {:estacao => { "nome" => "invalid value" }}, valid_session
        assigns(:estacao).should be_a_new(Estacao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estacao.any_instance.stub(:save).and_return(false)
        post :create, {:estacao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested estacao" do
        estacao = Estacao.create! valid_attributes
        # Assuming there are no other estacaos in the database, this
        # specifies that the Estacao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Estacao.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => estacao.to_param, :estacao => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested estacao as @estacao" do
        estacao = Estacao.create! valid_attributes
        put :update, {:id => estacao.to_param, :estacao => valid_attributes}, valid_session
        assigns(:estacao).should eq(estacao)
      end

      it "redirects to the estacao" do
        estacao = Estacao.create! valid_attributes
        put :update, {:id => estacao.to_param, :estacao => valid_attributes}, valid_session
        response.should redirect_to(estacao)
      end
    end

    describe "with invalid params" do
      it "assigns the estacao as @estacao" do
        estacao = Estacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => estacao.to_param, :estacao => { "nome" => "invalid value" }}, valid_session
        assigns(:estacao).should eq(estacao)
      end

      it "re-renders the 'edit' template" do
        estacao = Estacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => estacao.to_param, :estacao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estacao" do
      estacao = Estacao.create! valid_attributes
      expect {
        delete :destroy, {:id => estacao.to_param}, valid_session
      }.to change(Estacao, :count).by(-1)
    end

    it "redirects to the estacaos list" do
      estacao = Estacao.create! valid_attributes
      delete :destroy, {:id => estacao.to_param}, valid_session
      response.should redirect_to(estacaos_url)
    end
  end

end
