require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TremlinhasController do

  # This should return the minimal set of attributes required to create a valid
  # Tremlinha. As you add validations to Tremlinha, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "destino" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TremlinhasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tremlinhas as @tremlinhas" do
      tremlinha = Tremlinha.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tremlinhas).should eq([tremlinha])
    end
  end

  describe "GET show" do
    it "assigns the requested tremlinha as @tremlinha" do
      tremlinha = Tremlinha.create! valid_attributes
      get :show, {:id => tremlinha.to_param}, valid_session
      assigns(:tremlinha).should eq(tremlinha)
    end
  end

  describe "GET new" do
    it "assigns a new tremlinha as @tremlinha" do
      get :new, {}, valid_session
      assigns(:tremlinha).should be_a_new(Tremlinha)
    end
  end

  describe "GET edit" do
    it "assigns the requested tremlinha as @tremlinha" do
      tremlinha = Tremlinha.create! valid_attributes
      get :edit, {:id => tremlinha.to_param}, valid_session
      assigns(:tremlinha).should eq(tremlinha)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tremlinha" do
        expect {
          post :create, {:tremlinha => valid_attributes}, valid_session
        }.to change(Tremlinha, :count).by(1)
      end

      it "assigns a newly created tremlinha as @tremlinha" do
        post :create, {:tremlinha => valid_attributes}, valid_session
        assigns(:tremlinha).should be_a(Tremlinha)
        assigns(:tremlinha).should be_persisted
      end

      it "redirects to the created tremlinha" do
        post :create, {:tremlinha => valid_attributes}, valid_session
        response.should redirect_to(Tremlinha.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tremlinha as @tremlinha" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tremlinha.any_instance.stub(:save).and_return(false)
        post :create, {:tremlinha => { "destino" => "invalid value" }}, valid_session
        assigns(:tremlinha).should be_a_new(Tremlinha)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tremlinha.any_instance.stub(:save).and_return(false)
        post :create, {:tremlinha => { "destino" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tremlinha" do
        tremlinha = Tremlinha.create! valid_attributes
        # Assuming there are no other tremlinhas in the database, this
        # specifies that the Tremlinha created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tremlinha.any_instance.should_receive(:update).with({ "destino" => "MyString" })
        put :update, {:id => tremlinha.to_param, :tremlinha => { "destino" => "MyString" }}, valid_session
      end

      it "assigns the requested tremlinha as @tremlinha" do
        tremlinha = Tremlinha.create! valid_attributes
        put :update, {:id => tremlinha.to_param, :tremlinha => valid_attributes}, valid_session
        assigns(:tremlinha).should eq(tremlinha)
      end

      it "redirects to the tremlinha" do
        tremlinha = Tremlinha.create! valid_attributes
        put :update, {:id => tremlinha.to_param, :tremlinha => valid_attributes}, valid_session
        response.should redirect_to(tremlinha)
      end
    end

    describe "with invalid params" do
      it "assigns the tremlinha as @tremlinha" do
        tremlinha = Tremlinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tremlinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => tremlinha.to_param, :tremlinha => { "destino" => "invalid value" }}, valid_session
        assigns(:tremlinha).should eq(tremlinha)
      end

      it "re-renders the 'edit' template" do
        tremlinha = Tremlinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tremlinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => tremlinha.to_param, :tremlinha => { "destino" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tremlinha" do
      tremlinha = Tremlinha.create! valid_attributes
      expect {
        delete :destroy, {:id => tremlinha.to_param}, valid_session
      }.to change(Tremlinha, :count).by(-1)
    end

    it "redirects to the tremlinhas list" do
      tremlinha = Tremlinha.create! valid_attributes
      delete :destroy, {:id => tremlinha.to_param}, valid_session
      response.should redirect_to(tremlinhas_url)
    end
  end

end
